services:
  db:
    # Imagem mais atualizada do Banco postgresql
    image: postgres
    restart: always
    shm_size: 512mb

    environment:
      # Ambiente
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      
    expose:
      # Porta exposta conforme documentação da imagem
      - "${POSTGRES_PORT}"

    volumes:
      # Voume do banco
      - ./volumedb:/home/backups

    ports:
      # Porta de acesso
      - "${POSTGRES_PORT}:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080